# -- #
# Discord Region

# Discord Bot Token
bot_token: ""
# Discord Bot Prefix
bot_prefix: ""
# Discord Bot Owner ID
bot_owner_id: ""
# Discord Bot Guild ID
bot_guild_id: ""
# Max number of simultaneously connected users:
max_chats: ""
# Chat category
chat_category_id: ""
# Discord normal member role:
member_role_id: ""
# Panel channel id
panel_channel_id: ""

# -- #
# End Discord Region

# -- #
# OpenAI Region

# OpenAI API Key
openai_key: ""
# AI Engine (default: "text-davinci-003")
ai_engine: ""
# AI Temperature (0-1)
temperature: ""

# -- #
# End OpenAI Region

# -- #
# Start Database Region

# Database host:
db_host: ""
# Database Name:
db_name: ""
# Database User:
db_user: ""
# Database Pass:
db_pass: ""

# -- #
# End Database Region